---

- name: Install python-apt
  apt:
    name: python-apt
    state: present
    force: yes

- name: Add nginx repo
  apt_repository:
    repo: "{{ nginx_repo }}"
    state: present
    mode: 0644

- name: Install nginx
  apt:
    name: "{{ item }}"
    state: latest
    force: yes
  with_items: "{{ nginx_packages }}"
  notify: Start nginx
