---
# Nginx role main task file

# Role ansible dependencies
- name: Install python-apt
  apt:
    name: python-apt
    state: present
    force: yes

- include: install_nginx.yml
- include: configure_nginx.yml
