---
# Nginx role main task file
- include: install_nginx_ubuntu.yml
  when: ansible_os_family == "Debian"
- include: install_nginx_archlinux.yml
  when: ansible_os_family == "Archlinux"

- include: configure_nginx.yml
